FROM ruby:3.0.6-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libpq-dev postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000

CMD ["sh", "-c", "rm -f /rails/tmp/pids/server.pid && bundle exec rails db:prepare && ([ \"$RAILS_ENV\" = \"development\" ] && bundle exec rails db:seed || true) && bundle exec rails server -b 0.0.0.0 -p 3000"]
